version: "3.3"
services:
  cassandra-one:
    image: library/cassandra:3.11.10
    ports:
      - "9043:9042"
    environment:
      MAX_HEAP_SIZE: "400M"
      MIN_HEAP_SIZE: "400M"
      HEAP_NEWSIZE: "48M"
      CASSANDRA_ENABLE_SCRIPTED_USER_DEFINED_FUNCTIONS: "true"
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: "true"
    volumes:
      - ../cassandra-docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
