version: "3.3"
services:
  redis-one:
    image: library/redis:5.0.9
    ports:
      - "6379:6379"
  cassandra-one:
    image: library/cassandra:3.11.10
    ports:
      - "9043:9042"
    environment:
      MAX_HEAP_SIZE: "128M"
      MIN_HEAP_SIZE: "128M"
      HEAP_NEWSIZE: "24M"
      CASSANDRA_ENABLE_SCRIPTED_USER_DEFINED_FUNCTIONS: "true"
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: "true"
    volumes:
      - ../cassandra-docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
