version: "3.3"
services:
  redis-one:
    image: library/redis:5.0.9
    ports:
      - "6378:6379"
  cassandra-one:
    image: library/cassandra:3.11.6
    ports:
      - "9043:9042"
    environment:
      MAX_HEAP_SIZE: "128M"
      MIN_HEAP_SIZE: "128M"
      HEAP_NEWSIZE: "24M"
  zookeeper-one:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-one:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
