version: "3.3"
services:
  cassandra-one:
    image: bitnami/cassandra:4.0.6
    ports:
      - "9042:9042"
    environment:
      MAX_HEAP_SIZE: "400M"
      MIN_HEAP_SIZE: "400M"
      HEAP_NEWSIZE: "48M"
      CASSANDRA_ENABLE_SCRIPTED_USER_DEFINED_FUNCTIONS: "true"
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: "true"
      CASSANDRA_INIT_MAX_RETRIES: "500"
      CASSANDRA_INIT_SLEEP_TIME: "1"
      CASSANDRA_KEYSTORE_PASSWORD: "password"
      CASSANDRA_TRUSTSTORE_PASSWORD: "password"
      CASSANDRA_CLIENT_ENCRYPTION: "true"
    volumes:
      - ./certs/keystore.p12:/bitnami/cassandra/secrets/keystore
      - ./certs/truststore.p12:/bitnami/cassandra/secrets/truststore
      - type: tmpfs
        target: /bitnami/cassandra
