[profile.default]
fail-fast = false
slow-timeout = { period = '5m', terminate-after = 2 }
archive.include = [
    { path = "debug/jassets", relative-to = "target" },
    { path = "release/jassets", relative-to = "target" },
]

# Overwrites profile.default when the filter matches
[[profile.default.overrides]]
filter = 'package(shotover-proxy) | package(custom-transforms-example)'
test-group = 'integration-tests'

[test-groups]
integration-tests = { max-threads = 1 }
