---
sources:
  - Valkey:
      name: "redis"
      listen_addr: "127.0.0.1:6379"
      chain:
        - RedisGetRewrite:
            result: "Rewritten value"
        - RedisSinkSingle:
            remote_address: "127.0.0.1:1111"
            connect_timeout_ms: 3000
