version: "3.3"

networks:
  cassandra_subnet:
    name: cassandra_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1

services:
  cassandra-one:
    image: library/cassandra:4.0
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.2
    healthcheck: &healthcheck
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    environment: &environment
      CASSANDRA_SEEDS: "cassandra-one,cassandra-two"
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      MAX_HEAP_SIZE: "400M"
      MIN_HEAP_SIZE: "400M"
      HEAP_NEWSIZE: "48M"

  cassandra-two:
    image: library/cassandra:4.0
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.3
    healthcheck: *healthcheck
    environment: *environment
    depends_on:
      - cassandra-one

  cassandra-three:
    image: library/cassandra:4.0
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.4
    healthcheck: *healthcheck
    environment: *environment
    depends_on:
      - cassandra-two

  shotover-0:
    restart: always
    depends_on:
      - cassandra-one
    image: shotover-proxy
    network_mode: "service:cassandra-one"
    volumes:
      - type: bind
        source: $PWD
        target: /config

  shotover-1:
    restart: always
    depends_on:
      - cassandra-two
    image: shotover-proxy
    network_mode: "service:cassandra-two"
    volumes:
      - type: bind
        source: $PWD
        target: /config

  shotover-2:
    restart: always
    depends_on:
      - cassandra-three
    image: shotover-proxy
    network_mode: "service:cassandra-three"
    volumes:
      - type: bind
        source: $PWD
        target: /config
