name: MicroBenchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

# Cancel already running jobs
concurrency:
  group: benchmark_run_${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: step-security/rust-cache@9be15b830520fab0ec3939586e917e4855cf76bd # v2.8.3
        with:
          # this line means that only the main branch writes to the cache
          # benefits:
          # * prevents main branch caches from being evicted in favor of a PR cache
          # * saves about 1min per workflow by skipping the actual cache write
          # downsides:
          # * PRs that update rust version or changes deps will be slow to iterate on due to changes not being cached.
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install codspeed
        uses: taiki-e/install-action@bfadeaba214680fb4ab63e710bcb2a6a17019fdc # v2.70.4
        with:
          tool: cargo-codspeed@4.3.0

      - name: Build the benchmark target(s)
        # specify `--jobs 2` to avoid OoM on 4 core (and therefore 4 jobs) linux runners
        run: cargo codspeed build --jobs 2 --features alpha-transforms

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@d872884a306dd4853acf0f584f4b706cf0cc72a2 # v4.13.0
        with:
          mode: simulation
          run: cargo codspeed run