name: Formatting and lints

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: lints_${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  job:
    name: Formatting and lints
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: step-security/rust-cache@9be15b830520fab0ec3939586e917e4855cf76bd # v2.8.3
        with:
          # this line means that only the main branch writes to the cache
          # benefits:
          # * prevents main branch caches from being evicted in favor of a PR cache
          # * saves about 1min per workflow by skipping the actual cache write
          # downsides:
          # * PRs that update rust version or changes deps will be slow to iterate on due to changes not being cached.
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: cache custom ubuntu packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: shotover-proxy/build/packages
          key: ubuntu-24.04-packages
      - name: Install ubuntu packages
        run: shotover-proxy/build/install_ubuntu_packages.sh
      - name: Install cargo-hack
        uses: taiki-e/install-action@bfadeaba214680fb4ab63e710bcb2a6a17019fdc # v2.70.4
        with:
          tool: cargo-hack@0.6.16
      - name: Ensure `cargo fmt --all` was run
        run: cargo fmt --all -- --check
      - name: Ensure that all crates compile and have no warnings under every possible combination of features
        # some things to explicitly point out:
        # * clippy also reports rustc warnings and errors
        # * clippy --all-targets causes clippy to run against tests and examples which it doesnt do by default.
        run: cargo hack --feature-powerset --at-least-one-of valkey,cassandra,kafka,opensearch clippy --all-targets --locked -- -D warnings
      - name: Report disk usage
        run: |
          df -h
          
          echo -e "\ntarget dir usage:"
          du -h $PWD/target
          
          echo -e "\n.cargo dir usage:"
          du -h ~/.cargo
      - name: Ensure that tests did not create or modify any files that arent .gitignore'd
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status
            exit 1
          fi
