---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  prepublish-check:
    name: "Check that the project is releaseable"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ubuntu packages
        run: shotover-proxy/build/install_ubuntu_packages.sh
      - name: Run checks
        run: shotover-proxy/build/is_releasable.sh

  publish-image:
    name: "Publish Docker Image to Docker Hub"
    needs: prepublish-check
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Push image
        run: |
          docker build -t shotover/shotover-proxy:latest -t shotover/shotover-proxy:${GITHUB_REF/refs\/tags\//} .
          docker push shotover/shotover-proxy:latest
          docker push shotover/shotover-proxy:${GITHUB_REF/refs\/tags\//}

  publish-binary:
    name: "Publish Binary to GitHub"
    needs: prepublish-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ubuntu packages
        run: shotover-proxy/build/install_ubuntu_packages.sh
      - name: Build & test
        run: shotover-proxy/build/build_release.sh
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.tar.gz

  publish-crates-io:
    name: "Publish to crates.io"
    needs: prepublish-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ubuntu packages
        run: shotover-proxy/build/install_ubuntu_packages.sh
      - name: Publish
        run: |
          cd shotover
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
